#!/usr/bin/env bash
# create a certificate and configure HAproxy

global
        log /dev/log local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon
        tune.ssl.default-dh-param 2048
        # Default SSL material locations
        ca-base /etc/ssl/certs
        crt-base /etc/ssl/private

defaults
        log global
        mode http
        option httplog
        option dontlognull
        retries 3
        option redispatch
        timeout connect 5000
        timeout client 10000
        timeout server 10000
        option forwardfor
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http
        bind *:80
        http-request set-header X-Forwarded-Proto http
        default_backend web-servers

frontend www-https
        bind *:443 ssl crt /etc/letsencrypt/live/www.joumanaarafa.tech/www.joumanaarafa.tech.pem
        http-request set-header X-Forwarded-Proto https
        default_backend web-servers

backend web-servers
        balance roundrobin
        redirect scheme https if !{ ssl_fc }
        server 409195-web-01 54.208.140.192:80 check
        server 409195-web-02 18.210.10.70:80 check
