#!/usr/bin/env bash
# Transfers a file from client to server

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit;
fi

FILE_PATH="$1";
IP="$2";
USERNAME="$3";
PATH_pk="$4";

scp -o StrictHostKeyChecking=no -i "$PATH_pk" "$FILE_PATH" "${USERNAME}"@"${IP}":~/
