#!/usr/bin/env bash
# Installs Nginx according to requirements on ubuntu server

sudo apt-get update -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sudo service nginx restart
