#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y haproxy

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

sudo tee /etc/haproxy/haproxy.cfg > /dev/null << 'EOF'
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 10000
    timeout server 10000

listen hbnb
    bind 35.174.209.48:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 409195-web-01 54.208.140.192:80 check
    server 409195-web-02 18.210.10.70:80 check
EOF


sudo service haproxy start

